@base_url = http://localhost:8081
@id = 1

GET {{base_url}} HTTP/1.1

###

# @name create
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "name": "New Folder",
    "type": "folder",
    "user_id": 2
}

@id = {{create.response.body.ID}}

###

GET {{base_url}}/{{id}} HTTP/1.1

###

PUT {{base_url}}/{{id}} HTTP/1.1
Content-Type: application/json

{
    "name": "New Folder",
    "type": "folder",
    "user_id": 2
}

###

DELETE {{base_url}}/{{id}} HTTP/1.1
